# Generated by Django 6.0 on 2026-05-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titulo',
            new_name='title',
        ),
    ]
